
x-common-networks:
  &networks
  networks:
    - net

x-common-restart:
  &restart
  restart: always


services:
  backend:
    <<: [ *restart, *networks ]
    container_name: player-backend-api
    hostname: backend-api
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ./backend:/app
    command: bash docker-entrypoint.sh
    ports:
      - 7878:8000

  backend-redis:
    <<: [ *restart, *networks ]
    container_name: player-backend-redis
    hostname: backend-redis
    image: redis:latest


networks:
  net:
    name: ${PROJECT_NAME}-net
    driver: bridge

