
x-common-networks:
  &networks
  networks:
    - net

x-common-restart:
  &restart
  restart: always


services:
  backend:
    <<: [ *restart, *networks ]
    container_name: player-backend-api
    hostname: backend-api
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ./backend:/app
      - ./supervisord.conf:/etc/supervisor/conf.d/supervisord.conf:rw
    command: bash docker-entrypoint.sh

  backend-redis:
    <<: [ *restart, *networks ]
    container_name: player-backend-redis
    hostname: backend-redis
    image: redis:latest

  backend-nginx:
    <<: [ *restart, *networks]
    container_name: player-backend-nginx
    image: nginx:latest
    hostname: player-backend-nginx
    ports:
      - "7878:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./frontend:/src

networks:
  net:
    name: player-backend-net
    driver: bridge

